name = "morleys"
version = "0.1.0"
defaultTargets = ["morleys"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.21.0"

[[lean_lib]]
name = "Morleys"

[[lean_exe]]
name = "morleys"
root = "Main"
